#!/bin/bash
# flash-base.sh - macOS: flash Raspberry Pi OS Bookworm Lite (32-bit) to an SD
# card and pre-configure it for the IMX708 trap build (user, Wi-Fi, SSH, I2C,
# camera overlay).
#
# Usage:
#   ./flash-base.sh --ssid <wifi-ssid> --pass <wifi-password> [options]
#
# Options:
#   --ssid <ssid>        Wi-Fi network the Pi should join (required)
#   --pass <password>    Wi-Fi password (required)
#   --country <cc>       Wi-Fi country code (default: IL)
#   --image <path>       Path to a raspios .img.xz (default: auto-download latest)
#   --disk <diskN>       Target disk, e.g. disk4 (default: auto-detect external SD)
#   --build-password <p> Temporary password for user 'pi' (default: raspberry)
#
# The card is DESTROYED. The script shows the target disk and asks for
# confirmation before writing.

set -euo pipefail

# NOTE: the plain "latest" channel now serves Trixie (Debian 13). The trap
# stack is validated on Bookworm, which lives on the oldstable channel.
IMAGE_URL="https://downloads.raspberrypi.com/raspios_oldstable_lite_armhf_latest"
IMAGE_PATH=""
DISK=""
SSID=""
WIFI_PASS=""
COUNTRY="IL"
BUILD_PASSWORD="raspberry"
HOSTNAME="raspberrypi"
TIMEZONE="Asia/Jerusalem"
DOWNLOAD_DIR="$HOME/Downloads"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --ssid) SSID="$2"; shift 2;;
        --pass) WIFI_PASS="$2"; shift 2;;
        --country) COUNTRY="$2"; shift 2;;
        --image) IMAGE_PATH="$2"; shift 2;;
        --disk) DISK="$2"; shift 2;;
        --build-password) BUILD_PASSWORD="$2"; shift 2;;
        *) echo "Unknown argument: $1"; exit 1;;
    esac
done

if [[ -z "$SSID" || -z "$WIFI_PASS" ]]; then
    echo "ERROR: --ssid and --pass are required (the Pi must reach the internet on first boot)."
    exit 1
fi

# --- 1. Get the OS image -----------------------------------------------------
if [[ -z "$IMAGE_PATH" ]]; then
    IMAGE_PATH="$DOWNLOAD_DIR/raspios-bookworm-lite-armhf.img.xz"
    if [[ ! -f "$IMAGE_PATH" ]]; then
        echo ">>> Downloading Raspberry Pi OS Lite (32-bit, Bookworm)..."
        curl -L --fail -o "$IMAGE_PATH" "$IMAGE_URL"
    else
        echo ">>> Using cached image: $IMAGE_PATH"
    fi
fi
if [[ ! -f "$IMAGE_PATH" ]]; then
    echo "ERROR: image not found: $IMAGE_PATH"
    exit 1
fi

# --- 2. Find the SD card -----------------------------------------------------
if [[ -z "$DISK" ]]; then
    echo ">>> Looking for an external SD card..."
    CANDIDATES=$(diskutil list external physical | awk '/^\/dev\/disk/{print $1}' | sed 's|/dev/||')
    COUNT=$(echo "$CANDIDATES" | grep -c . || true)
    if [[ "$COUNT" -eq 0 ]]; then
        echo "ERROR: no external disk found. Insert the SD card (or pass --disk diskN)."
        exit 1
    elif [[ "$COUNT" -gt 1 ]]; then
        echo "ERROR: multiple external disks found; specify one with --disk diskN:"
        echo "$CANDIDATES"
        exit 1
    fi
    DISK="$CANDIDATES"
fi

echo
echo "======================== TARGET DISK ========================"
diskutil list "/dev/$DISK"
echo "============================================================="
echo
read -r -p "ALL DATA on /dev/$DISK will be ERASED. Type 'yes' to continue: " CONFIRM
if [[ "$CONFIRM" != "yes" ]]; then
    echo "Aborted."
    exit 1
fi

# --- 3. Flash ----------------------------------------------------------------
echo ">>> Unmounting /dev/$DISK"
diskutil unmountDisk "/dev/$DISK"

echo ">>> Writing image (this takes several minutes)..."
if [[ "$IMAGE_PATH" == *.xz ]]; then
    xz -dc "$IMAGE_PATH" | sudo dd of="/dev/r$DISK" bs=4m status=progress
else
    sudo dd if="$IMAGE_PATH" of="/dev/r$DISK" bs=4m status=progress
fi
sync

# --- 4. Mount boot partition and configure -----------------------------------
echo ">>> Re-mounting boot partition"
diskutil mountDisk "/dev/$DISK"
sleep 2
BOOT_MOUNT=""
for vol in /Volumes/bootfs /Volumes/boot; do
    if [[ -d "$vol" ]]; then BOOT_MOUNT="$vol"; break; fi
done
if [[ -z "$BOOT_MOUNT" ]]; then
    echo "ERROR: boot partition not found under /Volumes (expected bootfs/boot)."
    exit 1
fi
echo ">>> Boot partition: $BOOT_MOUNT"

echo ">>> Writing custom.toml (user/Wi-Fi/SSH/locale)"
cat > "$BOOT_MOUNT/custom.toml" <<EOF
# Raspberry Pi OS Bookworm first-boot configuration (generated by flash-base.sh)
config_version = 1

[system]
hostname = "$HOSTNAME"

[user]
name = "pi"
password = "$BUILD_PASSWORD"
password_encrypted = false

[ssh]
enabled = true
password_authentication = true

[wlan]
ssid = "$SSID"
password = "$WIFI_PASS"
password_encrypted = false
hidden = false
country = "$COUNTRY"

[locale]
keymap = "us"
timezone = "$TIMEZONE"
EOF

touch "$BOOT_MOUNT/ssh"

echo ">>> Enabling IMX708 overlay + I2C in config.txt"
if ! grep -q "dtoverlay=imx708" "$BOOT_MOUNT/config.txt"; then
    cat >> "$BOOT_MOUNT/config.txt" <<'EOF'

[all]
# IMX708 trap: 12MP Camera Module 3 + I2C (Witty Pi 4, SHT30)
dtoverlay=imx708
dtparam=i2c_arm=on
EOF
fi

sync
diskutil eject "/dev/$DISK"

echo
echo "Done. Next steps:"
echo "  1. Insert the card into the master Pi (camera attached) and power on."
echo "  2. First boot takes 2-4 minutes (filesystem expand + config, then reboot)."
echo "  3. ssh pi@$HOSTNAME.local  (password: $BUILD_PASSWORD)"
echo "  4. Run ./build-golden.sh setup pi@$HOSTNAME.local"
